---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: detect-private-key
      #- id: check-yaml # we use yamllint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.22.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml|j2)$
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - ansible-core==2.15.6  # keep this in sync with the version from the Makefile
          - ansible==8.6.0  # keep this in sync with the version from the Makefile
          - ansible-compat==4.1.10  # FIXME: ITSUP-55879 ITSUP-55055 remove as soon as ansible-lint is updated
          - jmespath
