---
- name: Converge
  hosts: all
  vars:
    dnsbltestlists:
      - https://raw.githubusercontent.com/Rosa-Luxemburgstiftung-Berlin/ansible-role-unbound/main/molecule/default/testdnsbl.txt
    dnsbl_lists: "{% if molecule_skip_rebuild_all | default(false) %}{{ dnsbl_lists_available + dnsbltestlists }}{% else %}{{ dnsbltestlists }}{% endif %}"
    dnsbl_match_subdomains: true
    dnsbl_exclude_domains:
      - repo.zero-sys.net
  tasks:
    - name: "Include rls.unbound"
      include_role:
        name: "rls.unbound"
    - name: fetch unbound-dnsbl-updater.py
      ansible.builtin.fetch:
        src: /etc/unbound/unbound-dnsbl-updater.py
        dest: /tmp/unbound-dnsbl-updater.py
        flat: true
      when: fetch_dnsbl_updater | default(false) | bool
