---
- name: Converge
  hosts: all
  vars:
    dnsbl_lists_str: "[ {% if fetch_dnsbl_updater is defined and fetch_dnsbl_updater %}'https://adaway.org/hosts.txt'{% endif %} ]"
    dnsbl_lists: "{{ dnsbl_lists_str | from_json }}"
  tasks:
    - name: "Include rls.unbound"
      include_role:
        name: "rls.unbound"
    - name: fetch unbound-dnsbl-updater.py
      ansible.builtin.fetch:
        src: /etc/unbound/unbound-dnsbl-updater.py
        dest: /tmp/unbound-dnsbl-updater.py
        flat: true
      when: fetch_dnsbl_updater | default(false) | bool
