---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: resolve domains
    set_fact:
      ip1: "{{ lookup('community.general.dig', 'zero-sys.net.', '@'+ansible_default_ipv4.address) }}"
      ip2: "{{ lookup('community.general.dig', 'test.github.com.', '@'+ansible_default_ipv4.address) }}"
  - name: debug ip1
    debug:
      var: ip1
  - name: debug ip2
    debug:
      var: ip2
  - name: test results
    assert:
      that:
        - ip1 == '65.108.89.174'
        - ip2 == '10.10.10.10'
