---
name: molecule test
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 6 * * 1"

defaults:
  run:
    working-directory: rls.unbound

jobs:
  molecule:
    name: ansible
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          #- latest
          - 13
          - 12
          - 11
          - 2.9
        distro:
          - debian12
          - debian13
        moleculescenario:
          - default
          - redirect
          - redirect-cname
        include:
          #- ansible: latest
          #  pip3deps: '"ansible>=14" "ansible-core>=2.21" molecule "molecule-plugins[docker]" yamllint ansible-lint requests==2.32.4 dnspython'
          #  pythonversion: 3.13.5
          - ansible: 13
            pip3deps: '"ansible>=13,<14" "ansible-core>=2.20,<2.21" molecule "molecule-plugins[docker]" yamllint ansible-lint requests==2.32.4 dnspython'
            pythonversion: 3.13.5
          - ansible: 12
            pip3deps: '"ansible>=12,<13" molecule "molecule-plugins[docker]" yamllint ansible-lint requests==2.32.4 dnspython'
            pythonversion: 3.13.5
          - ansible: 11
            pip3deps: '"ansible>=11,<12" molecule "molecule-plugins[docker]" yamllint ansible-lint requests==2.32.4 dnspython'
            pythonversion: 3.13.5
          - ansible: 2.9
            pip3deps: '"ansible==2.9.27" "molecule[docker,lint]==3.2.3" "yamllint==1.24.2" "ansible-lint==4.2.0" "requests<2.29" "urllib3<2" dnspython'
            pythonversion: 3.9
        exclude:
          - ansible: 2.9
            distro: debian13
          - moleculescenario: redirect
            distro: debian13
          - moleculescenario: redirect-cname
            distro: debian13
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'rls.unbound'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.pythonversion }}

      - name: Install test dependencies.
        run: pip3 install ${{ matrix.pip3deps }}

      - name: Install collections required on ansible 2.9
        run: ansible-galaxy collection install community.general
        if: ${{ matrix.ansible == 'legacy' }}

      - name: debug
        run: |
          ansible --version
          echo "--------------------"
          python --version
          echo "--------------------"
          pip list
          echo "--------------------"
          pwd
          echo "--------------------"
          ls -1
          echo "--------------------"
          ls -l
          echo "--------------------"

      - name: run molecule tests
        run: molecule test --scenario-name ${{ matrix.moleculescenario }}
        working-directory: rls.unbound
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          molecule_skip_rebuild_all: true
          MOLECULE_DISTRO: ${{ matrix.distro }}
